// THIS FILE IS AUTO-GENERATED
export const themes = [
  { id: 'terminal', name: 'terminal', file: 'terminal' },
  { id: 'ms_cupcakes', name: 'ms cupcakes', file: 'ms_cupcakes' },
  { id: 'fledgling', name: 'fledgling', file: 'fledgling' },
  { id: 'solarized_osaka', name: 'solarized osaka', file: 'solarized_osaka' },
  { id: 'horizon', name: 'horizon', file: 'horizon' },
  { id: 'vaporwave', name: 'vaporwave', file: 'vaporwave' },
  { id: 'witch_girl', name: 'witch girl', file: 'witch_girl' },
  { id: 'vesper', name: 'vesper', file: 'vesper' },
  { id: 'gruvbox_light', name: 'gruvbox light', file: 'gruvbox_light' },
  { id: 'soaring_skies', name: 'soaring skies', file: 'soaring_skies' },
  { id: 'terra', name: 'terra', file: 'terra' },
  { id: 'camping', name: 'camping', file: 'camping' },
  { id: 'lil_dragon', name: 'lil dragon', file: 'lil_dragon' },
  { id: 'github', name: 'github', file: 'github' },
  { id: 'laser', name: 'laser', file: 'laser' },
  { id: 'desert_oasis', name: 'desert oasis', file: 'desert_oasis' },
  { id: 'honey', name: 'honey', file: 'honey' },
  { id: '9009', name: '9009', file: '9009' },
  { id: 'sweden', name: 'sweden', file: 'sweden' },
  { id: 'solarized_dark', name: 'solarized dark', file: 'solarized_dark' },
  { id: 'mizu', name: 'mizu', file: 'mizu' },
  { id: 'lilac_mist', name: 'lilac mist', file: 'lilac_mist' },
  { id: 'terror_below', name: 'terror below', file: 'terror_below' },
  { id: 'bingsu', name: 'bingsu', file: 'bingsu' },
  { id: 'botanical', name: 'botanical', file: 'botanical' },
  { id: 'iceberg_dark', name: 'iceberg dark', file: 'iceberg_dark' },
  { id: 'aether', name: 'aether', file: 'aether' },
  { id: 'modern_dolch_light', name: 'modern dolch light', file: 'modern_dolch_light' },
  { id: 'magic_girl', name: 'magic girl', file: 'magic_girl' },
  { id: 'mashu', name: 'mashu', file: 'mashu' },
  { id: 'dark_magic_girl', name: 'dark magic girl', file: 'dark_magic_girl' },
  { id: 'purpleish', name: 'purpleish', file: 'purpleish' },
  { id: 'dino', name: 'dino', file: 'dino' },
  { id: 'mint', name: 'mint', file: 'mint' },
  { id: 'rudy', name: 'rudy', file: 'rudy' },
  { id: 'dev', name: 'dev', file: 'dev' },
  { id: 'dollar', name: 'dollar', file: 'dollar' },
  { id: 'tangerine', name: 'tangerine', file: 'tangerine' },
  { id: 'onedark', name: 'onedark', file: 'onedark' },
  { id: 'red_dragon', name: 'red dragon', file: 'red_dragon' },
  { id: 'tiramisu', name: 'tiramisu', file: 'tiramisu' },
  { id: 'midnight', name: 'midnight', file: 'midnight' },
  { id: 'dots', name: 'dots', file: 'dots' },
  { id: 'ez_mode', name: 'ez mode', file: 'ez_mode' },
  { id: 'viridescent', name: 'viridescent', file: 'viridescent' },
  { id: 'blue_dolphin', name: 'blue dolphin', file: 'blue_dolphin' },
  { id: 'matrix', name: 'matrix', file: 'matrix' },
  { id: 'aurora', name: 'aurora', file: 'aurora' },
  { id: 'night_runner', name: 'night runner', file: 'night_runner' },
  { id: 'grape', name: 'grape', file: 'grape' },
  { id: 'incognito', name: 'incognito', file: 'incognito' },
  { id: 'taro', name: 'taro', file: 'taro' },
  { id: 'vscode', name: 'vscode', file: 'vscode' },
  { id: 'nord', name: 'nord', file: 'nord' },
  { id: 'iceberg_light', name: 'iceberg light', file: 'iceberg_light' },
  { id: 'wavez', name: 'wavez', file: 'wavez' },
  { id: 'husqy', name: 'husqy', file: 'husqy' },
  { id: 'pink_lemonade', name: 'pink lemonade', file: 'pink_lemonade' },
  { id: 'passion_fruit', name: 'passion fruit', file: 'passion_fruit' },
  { id: 'earthsong', name: 'earthsong', file: 'earthsong' },
  { id: 'dualshot', name: 'dualshot', file: 'dualshot' },
  { id: 'material', name: 'material', file: 'material' },
  { id: 'paper', name: 'paper', file: 'paper' },
  { id: 'metropolis', name: 'metropolis', file: 'metropolis' },
  { id: 'nebula', name: 'nebula', file: 'nebula' },
  { id: 'alpine', name: 'alpine', file: 'alpine' },
  { id: 'rgb', name: 'rgb', file: 'rgb' },
  { id: 'hanok', name: 'hanok', file: 'hanok' },
  { id: 'serika_dark', name: 'serika dark', file: 'serika_dark' },
  { id: 'snes', name: 'snes', file: 'snes' },
  { id: 'modern_ink', name: 'modern ink', file: 'modern_ink' },
  { id: 'muted', name: 'muted', file: 'muted' },
  { id: 'nautilus', name: 'nautilus', file: 'nautilus' },
  { id: 'cheesecake', name: 'cheesecake', file: 'cheesecake' },
  { id: 'dark_note', name: 'dark note', file: 'dark_note' },
  { id: 'miami_nights', name: 'miami nights', file: 'miami_nights' },
  { id: 'moonlight', name: 'moonlight', file: 'moonlight' },
  { id: 'darling', name: 'darling', file: 'darling' },
  { id: 'macroblank', name: 'macroblank', file: 'macroblank' },
  { id: 'pastel', name: 'pastel', file: 'pastel' },
  { id: 'terrazzo', name: 'terrazzo', file: 'terrazzo' },
  { id: 'catppuccin', name: 'catppuccin', file: 'catppuccin' },
  { id: 'spiderman', name: 'spiderman', file: 'spiderman' },
  { id: 'cy_red', name: 'cy red', file: 'cy_red' },
  { id: 'dark', name: 'dark', file: 'dark' },
  { id: 'pale_nimbus', name: 'pale nimbus', file: 'pale_nimbus' },
  { id: 'ishtar', name: 'ishtar', file: 'ishtar' },
  { id: 'retro', name: 'retro', file: 'retro' },
  { id: 'stealth', name: 'stealth', file: 'stealth' },
  { id: 'repose_dark', name: 'repose dark', file: 'repose_dark' },
  { id: 'iv_clover', name: 'iv clover', file: 'iv_clover' },
  { id: 'lime', name: 'lime', file: 'lime' },
  { id: 'blueberry_light', name: 'blueberry light', file: 'blueberry_light' },
  { id: 'fruit_chew', name: 'fruit chew', file: 'fruit_chew' },
  { id: 'olivia', name: 'olivia', file: 'olivia' },
  { id: 'mexican', name: 'mexican', file: 'mexican' },
  { id: 'diner', name: 'diner', file: 'diner' },
  { id: 'sewing_tin_light', name: 'sewing tin light', file: 'sewing_tin_light' },
  { id: 'carbon', name: 'carbon', file: 'carbon' },
  { id: 'cafe', name: 'cafe', file: 'cafe' },
  { id: 'future_funk', name: 'future funk', file: 'future_funk' },
  { id: 'fire', name: 'fire', file: 'fire' },
  { id: 'striker', name: 'striker', file: 'striker' },
  { id: 'monokai', name: 'monokai', file: 'monokai' },
  { id: '8008', name: '8008', file: '8008' },
  { id: 'cherry_blossom', name: 'cherry blossom', file: 'cherry_blossom' },
  { id: 'hedge', name: 'hedge', file: 'hedge' },
  { id: 'froyo', name: 'froyo', file: 'froyo' },
  { id: 'evil_eye', name: 'evil eye', file: 'evil_eye' },
  { id: 'deku', name: 'deku', file: 'deku' },
  { id: 'tron_orange', name: 'tron orange', file: 'tron_orange' },
  { id: 'alduin', name: 'alduin', file: 'alduin' },
  { id: 'dmg', name: 'dmg', file: 'dmg' },
  { id: 'dracula', name: 'dracula', file: 'dracula' },
  { id: 'metaverse', name: 'metaverse', file: 'metaverse' },
  { id: 'hammerhead', name: 'hammerhead', file: 'hammerhead' },
  { id: 'bushido', name: 'bushido', file: 'bushido' },
  { id: 'matcha_moccha', name: 'matcha moccha', file: 'matcha_moccha' },
  { id: 'modern_dolch', name: 'modern dolch', file: 'modern_dolch' },
  { id: 'creamsicle', name: 'creamsicle', file: 'creamsicle' },
  { id: 'strawberry', name: 'strawberry', file: 'strawberry' },
  { id: 'nord_light', name: 'nord light', file: 'nord_light' },
  { id: 'shadow', name: 'shadow', file: 'shadow' },
  { id: 'bento', name: 'bento', file: 'bento' },
  { id: 'menthol', name: 'menthol', file: 'menthol' },
  { id: 'our_theme', name: 'our theme', file: 'our_theme' },
  { id: 'vesper_light', name: 'vesper light', file: 'vesper_light' },
  { id: 'everblush', name: 'everblush', file: 'everblush' },
  { id: 'mr_sleeves', name: 'mr sleeves', file: 'mr_sleeves' },
  { id: 'retrocast', name: 'retrocast', file: 'retrocast' },
  { id: 'frozen_llama', name: 'frozen llama', file: 'frozen_llama' },
  { id: 'solarized_light', name: 'solarized light', file: 'solarized_light' },
  { id: 'bliss', name: 'bliss', file: 'bliss' },
  { id: 'repose_light', name: 'repose light', file: 'repose_light' },
  { id: 'anti_hero', name: 'anti hero', file: 'anti_hero' },
  { id: 'suisei', name: 'suisei', file: 'suisei' },
  { id: 'fundamentals', name: 'fundamentals', file: 'fundamentals' },
  { id: 'miami', name: 'miami', file: 'miami' },
  { id: 'sewing_tin', name: 'sewing tin', file: 'sewing_tin' },
  { id: 'fleuriste', name: 'fleuriste', file: 'fleuriste' },
  { id: 'rose_pine', name: 'rose pine', file: 'rose_pine' },
  { id: 'sonokai', name: 'sonokai', file: 'sonokai' },
  { id: 'trackday', name: 'trackday', file: 'trackday' },
  { id: 'milkshake', name: 'milkshake', file: 'milkshake' },
  { id: 'trance', name: 'trance', file: 'trance' },
  { id: 'sunset', name: 'sunset', file: 'sunset' },
  { id: 'superuser', name: 'superuser', file: 'superuser' },
  { id: 'rainbow_trail', name: 'rainbow trail', file: 'rainbow_trail' },
  { id: 'floret', name: 'floret', file: 'floret' },
  { id: 'serika', name: 'serika', file: 'serika' },
  { id: 'gruvbox_dark', name: 'gruvbox dark', file: 'gruvbox_dark' },
  { id: 'godspeed', name: 'godspeed', file: 'godspeed' },
  { id: 'joker', name: 'joker', file: 'joker' },
  { id: 'rose_pine_dawn', name: 'rose pine dawn', file: 'rose_pine_dawn' },
  { id: 'grand_prix', name: 'grand prix', file: 'grand_prix' },
  { id: 'lavender', name: 'lavender', file: 'lavender' },
  { id: 'watermelon', name: 'watermelon', file: 'watermelon' },
  { id: 'copper', name: 'copper', file: 'copper' },
  { id: 'beach', name: 'beach', file: 'beach' },
  { id: 'iv_spade', name: 'iv spade', file: 'iv_spade' },
  { id: 'pulse', name: 'pulse', file: 'pulse' },
  { id: 'drowning', name: 'drowning', file: 'drowning' },
  { id: 'blueberry_dark', name: 'blueberry dark', file: 'blueberry_dark' },
  { id: 'arch', name: 'arch', file: 'arch' },
  { id: 'olive', name: 'olive', file: 'olive' },
  { id: 'luna', name: 'luna', file: 'luna' },
  { id: 'red_samurai', name: 'red samurai', file: 'red_samurai' },
  { id: 'breeze', name: 'breeze', file: 'breeze' },
  { id: 'cyberspace', name: 'cyberspace', file: 'cyberspace' },
  { id: 'shoko', name: 'shoko', file: 'shoko' },
  { id: 'oblivion', name: 'oblivion', file: 'oblivion' },
  { id: 'comfy', name: 'comfy', file: 'comfy' },
  { id: 'chaos_theory', name: 'chaos theory', file: 'chaos_theory' },
  { id: 'peach_blossom', name: 'peach blossom', file: 'peach_blossom' },
  { id: 'bouquet', name: 'bouquet', file: 'bouquet' },
  { id: 'slambook', name: 'slambook', file: 'slambook' },
  { id: 'ryujinscales', name: 'ryujinscales', file: 'ryujinscales' },
  { id: 'graen', name: 'graen', file: 'graen' },
  { id: 'mountain', name: 'mountain', file: 'mountain' },
  { id: 'phantom', name: 'phantom', file: 'phantom' },
  { id: 'voc', name: 'voc', file: 'voc' },
  { id: 'leather', name: 'leather', file: 'leather' },
  { id: 'norse', name: 'norse', file: 'norse' },
  { id: 'discord', name: 'discord', file: 'discord' },
  { id: 'rose_pine_moon', name: 'rose pine moon', file: 'rose_pine_moon' },
  { id: '80s_after_dark', name: '80s after dark', file: '80s_after_dark' },
  { id: 'peaches', name: 'peaches', file: 'peaches' },
  { id: 'gdawg', name: 'the trees have a bunch of leaves and my bark has a lot of cracks but the greatest waters always leave from the goth girls', file: 'gdawg' }
];